name: mkdocs-deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry 1.4.0
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "1.4.0"

      - name: Install dependency
        run: poetry install

      - name: Run Mkdocs
        run: poetry run mkdocs gh-deploy --force
